import type { CatalogVenue } from "@/lifestyle/types";

const dinner: CatalogVenue["hours"] = { days: [0, 1, 2, 3, 4, 5, 6], open: "12:00", close: "23:30" };
const cafe: CatalogVenue["hours"] = { days: [0, 1, 2, 3, 4, 5, 6], open: "09:00", close: "00:00" };
const day: CatalogVenue["hours"] = { days: [0, 1, 2, 3, 4, 5, 6], open: "08:00", close: "22:00" };

function r(partial: Omit<CatalogVenue, "kind">): CatalogVenue {
  return { kind: "restaurant", hours: dinner, familyFriendly: true, delivery: true, ...partial };
}
function p(partial: Omit<CatalogVenue, "kind">): CatalogVenue {
  return { kind: "place", hours: day, familyFriendly: true, outdoor: true, ...partial };
}

export const CATALOG_VENUES: CatalogVenue[] = [
  r({ name: "The Monal", city: "Islamabad", area: "Pir Sohawa", cuisine: ["pakistani", "bbq"], categories: ["restaurant", "romantic", "outdoor", "view"], priceRange: "high", popularDishes: ["karahi", "bbq platter", "kunna"], outdoor: true, venueType: "view dining" }),
  r({ name: "Tuscany Courtyard", city: "Islamabad", area: "F-11", cuisine: ["italian", "continental"], categories: ["restaurant", "romantic", "quiet"], priceRange: "high", popularDishes: ["pasta", "steak", "pizza"], venueType: "fine dining" }),
  r({ name: "Chaaye Khana", city: "Islamabad", area: "F-7", cuisine: ["pakistani", "cafe"], categories: ["cafe", "casual", "outdoor"], priceRange: "medium", popularDishes: ["karak chai", "paratha", "club sandwich"], hours: cafe, venueType: "cafe" }),
  r({ name: "Ginyaki", city: "Islamabad", area: "F-7", cuisine: ["japanese", "asian"], categories: ["restaurant", "date", "food"], priceRange: "high", popularDishes: ["ramen", "sushi", "gyoza"], venueType: "japanese" }),
  r({ name: "Burning Brownie", city: "Islamabad", area: "F-7", cuisine: ["burgers", "american"], categories: ["casual", "food"], priceRange: "medium", popularDishes: ["smash burger", "brownie", "fries"], venueType: "burger" }),
  r({ name: "Savour Foods", city: "Islamabad", area: "Aabpara", cuisine: ["pakistani"], categories: ["casual", "budget", "family"], priceRange: "low", popularDishes: ["chicken karahi", "naan"], venueType: "local" }),
  p({ name: "Daman-e-Koh", city: "Islamabad", area: "Margalla Hills", categories: ["viewpoint", "outdoor", "date", "nature"], outdoor: true, venueType: "viewpoint" }),
  p({ name: "Pakistan Monument", city: "Islamabad", area: "Shakarparian", categories: ["historical", "family", "cultural"], venueType: "monument" }),
  p({ name: "Centaurus Mall", city: "Islamabad", area: "F-8", categories: ["shopping", "indoor", "entertainment", "family"], outdoor: false, venueType: "mall" }),
  p({ name: "Lok Virsa Museum", city: "Islamabad", area: "Shakarparian", categories: ["museum", "cultural", "indoor", "quiet"], outdoor: false, venueType: "museum" }),
  p({ name: "F-9 Park", city: "Islamabad", area: "F-9", categories: ["park", "outdoor", "family", "walk"], venueType: "park" }),
  p({ name: "Saidpur Village", city: "Islamabad", area: "Saidpur", categories: ["cultural", "date", "food", "outdoor"], venueType: "heritage village" }),
  r({ name: "Bundu Khan", city: "Islamabad", area: "F-10", address: "F-10 Markaz", cuisine: ["pakistani", "bbq"], categories: ["restaurant", "family", "casual"], priceRange: "medium", popularDishes: ["karahi", "bbq platter", "naan"], venueType: "desi" }),
  r({ name: "Hardee's F-10", city: "Islamabad", area: "F-10", address: "F-10 Markaz", cuisine: ["burgers", "fast food"], categories: ["casual", "budget", "food"], priceRange: "low", popularDishes: ["burger", "fries", "broast"], venueType: "burger" }),
  r({ name: "KFC Super Market", city: "Islamabad", area: "F-10", address: "Super Market F-10", cuisine: ["fast food", "burgers"], categories: ["casual", "budget"], priceRange: "low", popularDishes: ["zinger", "fries"], venueType: "fast food" }),
  r({ name: "Tehzeeb Bakers F-10", city: "Islamabad", area: "F-10", address: "F-10 Markaz", cuisine: ["bakery", "cafe", "pakistani"], categories: ["cafe", "breakfast", "casual"], priceRange: "low", popularDishes: ["chicken patties", "paratha", "chai"], hours: cafe, venueType: "bakery" }),
  r({ name: "McDonald's Super Market", city: "Islamabad", area: "F-10", address: "Super Market F-10", cuisine: ["burgers", "fast food"], categories: ["casual", "budget", "family"], priceRange: "low", popularDishes: ["burger", "fries"], venueType: "fast food" }),
  r({ name: "Street 1 Café", city: "Islamabad", area: "F-10", address: "F-10 Markaz", cuisine: ["cafe", "continental"], categories: ["cafe", "casual", "quiet"], priceRange: "medium", popularDishes: ["pasta", "coffee", "sandwich"], hours: cafe, venueType: "cafe" }),
  r({ name: "California Pizza F-10", city: "Islamabad", area: "F-10", address: "F-10 Markaz", cuisine: ["pizza", "italian"], categories: ["casual", "family", "food"], priceRange: "medium", popularDishes: ["pizza", "pasta"], venueType: "pizza" }),
  r({ name: "Ginsoy F-10", city: "Islamabad", area: "F-10", address: "F-10 Markaz", cuisine: ["chinese"], categories: ["restaurant", "family"], priceRange: "medium", popularDishes: ["drunken chicken", "fried rice"], venueType: "chinese" }),
  r({ name: "Howdy F-11", city: "Islamabad", area: "F-11", cuisine: ["burgers", "american"], categories: ["casual", "food"], priceRange: "medium", popularDishes: ["smash burger", "fries"], venueType: "burger" }),

  r({ name: "Mei Kong", city: "Rawalpindi", area: "Saddar", cuisine: ["chinese"], categories: ["restaurant", "family"], priceRange: "medium", popularDishes: ["chicken manchurian", "fried rice", "hot and sour"] }),
  r({ name: "KFC Saddar", city: "Rawalpindi", area: "Saddar", cuisine: ["fast food", "burgers"], categories: ["casual", "budget"], priceRange: "low", popularDishes: ["zinger", "fries"] }),
  r({ name: "Usmania Restaurant", city: "Rawalpindi", area: "Saddar", cuisine: ["pakistani", "bbq"], categories: ["family", "casual"], priceRange: "medium", popularDishes: ["mutton karahi", "bbq"] }),
  r({ name: "The Gourmet", city: "Rawalpindi", area: "Saddar", cuisine: ["bakery", "cafe"], categories: ["cafe", "dessert"], priceRange: "low", popularDishes: ["cake", "patisserie"], hours: cafe }),
  r({ name: "Tandoori", city: "Rawalpindi", area: "Bahria Town", cuisine: ["pakistani", "bbq"], categories: ["family", "casual"], priceRange: "medium", popularDishes: ["tikka", "naan"] }),
  p({ name: "Ayub Park", city: "Rawalpindi", categories: ["park", "family", "outdoor"], venueType: "park" }),
  p({ name: "Army Museum", city: "Rawalpindi", categories: ["museum", "family", "indoor"], outdoor: false, venueType: "museum" }),
  p({ name: "Raja Bazaar", city: "Rawalpindi", area: "Saddar", categories: ["shopping", "cultural"], venueType: "bazaar" }),
  p({ name: "Liaquat Bagh", city: "Rawalpindi", categories: ["park", "historical"], venueType: "park" }),
  p({ name: "Bahria Town Golf Club", city: "Rawalpindi", categories: ["outdoor", "quiet"], venueType: "club" }),

  r({ name: "Andaaz Restaurant", city: "Lahore", area: "Walled City", cuisine: ["pakistani"], categories: ["romantic", "view", "special"], priceRange: "high", popularDishes: ["dal", "naan", "lahori karahi"], outdoor: true }),
  r({ name: "Cuckoo's Den", city: "Lahore", area: "Food Street", cuisine: ["pakistani"], categories: ["romantic", "cultural", "outdoor"], priceRange: "medium", popularDishes: ["karahi", "kebab"] }),
  r({ name: "Butt Karahi", city: "Lahore", area: "Lakshmi Chowk", cuisine: ["pakistani"], categories: ["casual", "food"], priceRange: "medium", popularDishes: ["chicken karahi"] }),
  r({ name: "Yum Chinese & Thai", city: "Lahore", area: "Gulberg", cuisine: ["chinese", "thai"], categories: ["restaurant", "family"], priceRange: "medium", popularDishes: ["thai green curry", "dumplings"] }),
  r({ name: "Salt'n Pepper", city: "Lahore", area: "MM Alam", cuisine: ["pakistani", "chinese", "continental"], categories: ["family", "casual"], priceRange: "medium", popularDishes: ["fish", "steak", "chinese platter"] }),
  r({ name: "Howdy", city: "Lahore", area: "Packages Mall", cuisine: ["burgers", "american"], categories: ["casual", "food"], priceRange: "medium", popularDishes: ["smash burger", "fries"] }),
  p({ name: "Badshahi Mosque", city: "Lahore", area: "Walled City", categories: ["historical", "cultural", "family"], venueType: "heritage" }),
  p({ name: "Lahore Fort", city: "Lahore", area: "Walled City", categories: ["historical", "cultural"], venueType: "fort" }),
  p({ name: "Packages Mall", city: "Lahore", categories: ["shopping", "indoor", "entertainment", "family"], outdoor: false, venueType: "mall" }),
  p({ name: "Race Course Park", city: "Lahore", categories: ["park", "outdoor", "walk", "date"], venueType: "park" }),
  p({ name: "Shalimar Gardens", city: "Lahore", categories: ["historical", "outdoor", "quiet"], venueType: "garden" }),
  p({ name: "Wagah Border", city: "Lahore", categories: ["cultural", "adventure", "family"], venueType: "ceremony" }),

  r({ name: "Kolachi", city: "Karachi", area: "Do Darya", cuisine: ["pakistani", "seafood"], categories: ["romantic", "outdoor", "special"], priceRange: "high", popularDishes: ["bbq", "fish", "karahi"], outdoor: true }),
  r({ name: "BBQ Tonight", city: "Karachi", area: "Do Darya", cuisine: ["bbq", "pakistani"], categories: ["family", "outdoor"], priceRange: "medium", popularDishes: ["malai boti", "seekh kebab"] }),
  r({ name: "Xander's", city: "Karachi", area: "Clifton", cuisine: ["cafe", "continental"], categories: ["cafe", "casual", "quiet"], priceRange: "medium", popularDishes: ["pasta", "coffee", "waffles"], hours: cafe }),
  r({ name: "Okra", city: "Karachi", area: "Clifton", cuisine: ["continental", "fusion"], categories: ["romantic", "luxury", "quiet"], priceRange: "high", popularDishes: ["steak", "seafood"] }),
  r({ name: "Burns Road Food Street", city: "Karachi", area: "Burns Road", cuisine: ["pakistani", "dessert"], categories: ["casual", "budget", "food", "cultural"], priceRange: "low", popularDishes: ["nihari", "raabri", "bun kebab"] }),
  r({ name: "Ginsoy Extreme Chinese", city: "Karachi", area: "Clifton", cuisine: ["chinese"], categories: ["family", "casual"], priceRange: "medium", popularDishes: ["drunken chicken", "fried rice"] }),
  p({ name: "Clifton Beach", city: "Karachi", categories: ["outdoor", "nature", "date", "family"], venueType: "beach" }),
  p({ name: "Mohatta Palace", city: "Karachi", categories: ["museum", "cultural", "quiet"], outdoor: false, venueType: "museum" }),
  p({ name: "Port Grand", city: "Karachi", categories: ["entertainment", "food", "date", "outdoor"], venueType: "waterfront" }),
  p({ name: "Dolmen Mall Clifton", city: "Karachi", categories: ["shopping", "indoor", "family"], outdoor: false, venueType: "mall" }),
  p({ name: "Frere Hall", city: "Karachi", categories: ["historical", "park", "quiet"], venueType: "heritage" }),
  p({ name: "Hill Park", city: "Karachi", categories: ["park", "outdoor", "family"], venueType: "park" }),

  r({ name: "Chief Burger", city: "Peshawar", area: "University Road", cuisine: ["burgers"], categories: ["casual", "budget"], priceRange: "low", popularDishes: ["chapli burger", "fries"] }),
  r({ name: "Shiraz Restaurant", city: "Peshawar", area: "Saddar", cuisine: ["pakistani", "afghani"], categories: ["family", "casual"], priceRange: "medium", popularDishes: ["chapli kebab", "pulao"] }),
  r({ name: "Namak Mandi", city: "Peshawar", area: "Namak Mandi", cuisine: ["pakistani", "bbq"], categories: ["food", "cultural", "casual"], priceRange: "low", popularDishes: ["karahi", "tikka"] }),
  r({ name: "Charsi Tikka", city: "Peshawar", cuisine: ["bbq", "pakistani"], categories: ["casual", "food"], priceRange: "low", popularDishes: ["tikka", "naan"] }),
  r({ name: "Pizza Hut University Road", city: "Peshawar", cuisine: ["pizza", "italian"], categories: ["casual", "family"], priceRange: "medium", popularDishes: ["pizza", "pasta"] }),
  p({ name: "Bala Hisar Fort", city: "Peshawar", categories: ["historical", "cultural"], venueType: "fort" }),
  p({ name: "Qissa Khwani Bazaar", city: "Peshawar", categories: ["shopping", "cultural", "historical"], venueType: "bazaar" }),
  p({ name: "Peshawar Museum", city: "Peshawar", categories: ["museum", "cultural", "indoor"], outdoor: false, venueType: "museum" }),
  p({ name: "Islamia College Grounds", city: "Peshawar", categories: ["historical", "walk", "quiet"], venueType: "campus" }),
  p({ name: "Army Stadium Park", city: "Peshawar", categories: ["park", "family", "outdoor"], venueType: "park" }),

  r({ name: "Usmania Restaurant", city: "Quetta", cuisine: ["pakistani", "bbq"], categories: ["family", "casual"], priceRange: "medium", popularDishes: ["sajji", "karahi"] }),
  r({ name: "Lehri Sajji House", city: "Quetta", cuisine: ["pakistani", "bbq"], categories: ["food", "casual"], priceRange: "low", popularDishes: ["sajji"] }),
  r({ name: "Café Aylanto Quetta", city: "Quetta", cuisine: ["cafe", "continental"], categories: ["cafe", "quiet"], priceRange: "medium", hours: cafe, popularDishes: ["coffee", "pasta"] }),
  r({ name: "Impeccable Restaurant", city: "Quetta", cuisine: ["pakistani", "chinese"], categories: ["family"], priceRange: "medium", popularDishes: ["karahi", "chinese rice"] }),
  r({ name: "KFC Jinnah Road", city: "Quetta", cuisine: ["fast food"], categories: ["casual", "budget"], priceRange: "low", popularDishes: ["zinger"] }),
  p({ name: "Hanna Lake", city: "Quetta", categories: ["nature", "outdoor", "date"], venueType: "lake" }),
  p({ name: "Quetta Fort", city: "Quetta", categories: ["historical"], venueType: "fort" }),
  p({ name: "Hazarganji Chiltan National Park", city: "Quetta", categories: ["nature", "adventure", "outdoor"], venueType: "park" }),
  p({ name: "Askari Park", city: "Quetta", categories: ["park", "family"], venueType: "park" }),
  p({ name: "Liaquat Bazaar", city: "Quetta", categories: ["shopping", "cultural"], venueType: "bazaar" }),

  r({ name: "Bundu Khan", city: "Multan", cuisine: ["pakistani", "bbq"], categories: ["family", "casual"], priceRange: "medium", popularDishes: ["karahi", "bbq"] }),
  r({ name: "Savor Foods Multan", city: "Multan", cuisine: ["pakistani"], categories: ["casual", "budget"], priceRange: "low", popularDishes: ["karahi", "naan"] }),
  r({ name: "Pizza 365", city: "Multan", cuisine: ["pizza", "italian"], categories: ["casual", "family"], priceRange: "medium", popularDishes: ["pizza"] }),
  r({ name: "ChenOne Dine", city: "Multan", cuisine: ["continental", "pakistani"], categories: ["casual"], priceRange: "medium", popularDishes: ["pasta", "karahi"] }),
  r({ name: "Andaaz Multan", city: "Multan", cuisine: ["pakistani"], categories: ["family"], priceRange: "medium", popularDishes: ["sohan halwa pairing", "karahi"] }),
  p({ name: "Shrine of Bahauddin Zakariya", city: "Multan", categories: ["historical", "cultural"], venueType: "shrine" }),
  p({ name: "Multan Fort", city: "Multan", categories: ["historical"], venueType: "fort" }),
  p({ name: "Ghanta Ghar Chowk", city: "Multan", categories: ["cultural", "shopping"], venueType: "square" }),
  p({ name: "Shah Shams Park", city: "Multan", categories: ["park", "family", "outdoor"], venueType: "park" }),
  p({ name: "The Mall of Multan", city: "Multan", categories: ["shopping", "indoor", "family"], outdoor: false, venueType: "mall" }),

  r({ name: "Lasani Restaurant", city: "Faisalabad", cuisine: ["pakistani"], categories: ["family", "casual"], priceRange: "medium", popularDishes: ["karahi", "biryani"] }),
  r({ name: "Salt'n Pepper Faisalabad", city: "Faisalabad", cuisine: ["pakistani", "chinese"], categories: ["family"], priceRange: "medium", popularDishes: ["chinese platter", "steak"] }),
  r({ name: "Howdy Faisalabad", city: "Faisalabad", cuisine: ["burgers"], categories: ["casual"], priceRange: "medium", popularDishes: ["burger", "fries"] }),
  r({ name: "Bundu Khan Faisalabad", city: "Faisalabad", cuisine: ["bbq", "pakistani"], categories: ["family"], priceRange: "medium", popularDishes: ["bbq platter"] }),
  r({ name: "The Gourmet Faisalabad", city: "Faisalabad", cuisine: ["bakery", "cafe"], categories: ["cafe", "dessert"], priceRange: "low", hours: cafe, popularDishes: ["cake", "coffee"] }),
  p({ name: "Clock Tower", city: "Faisalabad", categories: ["historical", "cultural"], venueType: "landmark" }),
  p({ name: "Jinnah Garden", city: "Faisalabad", categories: ["park", "outdoor", "family"], venueType: "park" }),
  p({ name: "Lyallpur Museum", city: "Faisalabad", categories: ["museum", "indoor", "cultural"], outdoor: false, venueType: "museum" }),
  p({ name: "D-Ground", city: "Faisalabad", categories: ["shopping", "entertainment", "casual"], venueType: "market" }),
  p({ name: "Gatwala Forest Park", city: "Faisalabad", categories: ["nature", "outdoor", "family"], venueType: "park" }),

  r({ name: "Usmania Gujranwala", city: "Gujranwala", cuisine: ["pakistani"], categories: ["family"], priceRange: "medium", popularDishes: ["karahi"] }),
  r({ name: "Bundu Khan Gujranwala", city: "Gujranwala", cuisine: ["bbq"], categories: ["family"], priceRange: "medium", popularDishes: ["bbq"] }),
  r({ name: "Pizza Hut Gujranwala", city: "Gujranwala", cuisine: ["pizza"], categories: ["casual", "family"], priceRange: "medium", popularDishes: ["pizza"] }),
  r({ name: "Fri-Chicks", city: "Gujranwala", cuisine: ["fast food", "burgers"], categories: ["casual", "budget"], priceRange: "low", popularDishes: ["broast", "burger"] }),
  r({ name: "Ginsoy Gujranwala", city: "Gujranwala", cuisine: ["chinese"], categories: ["family"], priceRange: "medium", popularDishes: ["chinese rice"] }),
  p({ name: "Gulshan-e-Iqbal Park", city: "Gujranwala", categories: ["park", "family"], venueType: "park" }),
  p({ name: "Gujranwala Fort remnants", city: "Gujranwala", categories: ["historical"], venueType: "heritage" }),
  p({ name: "Kings Mall", city: "Gujranwala", categories: ["shopping", "indoor"], outdoor: false, venueType: "mall" }),
  p({ name: "Jinnah Stadium area", city: "Gujranwala", categories: ["outdoor", "family"], venueType: "grounds" }),
  p({ name: "Model Town Park", city: "Gujranwala", categories: ["park", "walk"], venueType: "park" }),

  r({ name: "Salt'n Pepper Sialkot", city: "Sialkot", cuisine: ["pakistani", "chinese"], categories: ["family"], priceRange: "medium", popularDishes: ["karahi", "chinese"] }),
  r({ name: "Howdy Sialkot", city: "Sialkot", cuisine: ["burgers"], categories: ["casual"], priceRange: "medium", popularDishes: ["burger"] }),
  r({ name: "Bundu Khan Sialkot", city: "Sialkot", cuisine: ["bbq"], categories: ["family"], priceRange: "medium", popularDishes: ["bbq platter"] }),
  r({ name: "The Gourmet Sialkot", city: "Sialkot", cuisine: ["cafe", "bakery"], categories: ["cafe"], priceRange: "low", hours: cafe, popularDishes: ["cake"] }),
  r({ name: "KFC Sialkot", city: "Sialkot", cuisine: ["fast food"], categories: ["casual", "budget"], priceRange: "low", popularDishes: ["zinger"] }),
  p({ name: "Iqbal Manzil", city: "Sialkot", categories: ["historical", "cultural", "museum"], venueType: "heritage" }),
  p({ name: "Sialkot Fort", city: "Sialkot", categories: ["historical"], venueType: "fort" }),
  p({ name: "Murray College grounds", city: "Sialkot", categories: ["walk", "quiet"], venueType: "campus" }),
  p({ name: "Jinnah Stadium Park", city: "Sialkot", categories: ["park", "family"], venueType: "park" }),
  p({ name: "Sialkot Clock Tower", city: "Sialkot", categories: ["historical", "cultural"], venueType: "landmark" }),

  r({ name: "Koel Café Hyderabad", city: "Hyderabad", cuisine: ["cafe", "pakistani"], categories: ["cafe", "casual"], priceRange: "medium", hours: cafe, popularDishes: ["biryani", "chai"] }),
  r({ name: "Student Biryani", city: "Hyderabad", cuisine: ["pakistani"], categories: ["casual", "budget", "food"], priceRange: "low", popularDishes: ["sindhi biryani"] }),
  r({ name: "Ginsoy Hyderabad", city: "Hyderabad", cuisine: ["chinese"], categories: ["family"], priceRange: "medium", popularDishes: ["chinese rice"] }),
  r({ name: "Pizza Hut Hyderabad", city: "Hyderabad", cuisine: ["pizza"], categories: ["casual"], priceRange: "medium", popularDishes: ["pizza"] }),
  r({ name: "BBQ Tonight Hyderabad", city: "Hyderabad", cuisine: ["bbq"], categories: ["family"], priceRange: "medium", popularDishes: ["bbq"] }),
  p({ name: "Rani Bagh", city: "Hyderabad", categories: ["park", "family", "outdoor"], venueType: "park" }),
  p({ name: "Pakka Qila", city: "Hyderabad", categories: ["historical"], venueType: "fort" }),
  p({ name: "Sindh Museum", city: "Hyderabad", categories: ["museum", "cultural", "indoor"], outdoor: false, venueType: "museum" }),
  p({ name: "Resham Gali", city: "Hyderabad", categories: ["shopping", "cultural"], venueType: "bazaar" }),
  p({ name: "Navalrai Clock Tower", city: "Hyderabad", categories: ["historical"], venueType: "landmark" }),

  r({ name: "Usmania Bahawalpur", city: "Bahawalpur", cuisine: ["pakistani"], categories: ["family"], priceRange: "medium", popularDishes: ["karahi"] }),
  r({ name: "Sadiq Restaurant", city: "Bahawalpur", cuisine: ["pakistani"], categories: ["casual"], priceRange: "low", popularDishes: ["biryani"] }),
  r({ name: "Pizza Hut Bahawalpur", city: "Bahawalpur", cuisine: ["pizza"], categories: ["casual"], priceRange: "medium", popularDishes: ["pizza"] }),
  r({ name: "Bundu Khan Bahawalpur", city: "Bahawalpur", cuisine: ["bbq"], categories: ["family"], priceRange: "medium", popularDishes: ["bbq"] }),
  r({ name: "The Gourmet Bahawalpur", city: "Bahawalpur", cuisine: ["cafe"], categories: ["cafe"], priceRange: "low", hours: cafe, popularDishes: ["cake"] }),
  p({ name: "Noor Mahal", city: "Bahawalpur", categories: ["historical", "cultural", "date"], venueType: "palace" }),
  p({ name: "Darbar Mahal", city: "Bahawalpur", categories: ["historical"], venueType: "palace" }),
  p({ name: "Bahawalpur Museum", city: "Bahawalpur", categories: ["museum", "indoor"], outdoor: false, venueType: "museum" }),
  p({ name: "Lal Suhanra National Park", city: "Bahawalpur", categories: ["nature", "adventure", "outdoor"], venueType: "park" }),
  p({ name: "Fawara Chowk", city: "Bahawalpur", categories: ["cultural", "walk"], venueType: "square" }),

  r({ name: "Usmania Abbottabad", city: "Abbottabad", cuisine: ["pakistani"], categories: ["family"], priceRange: "medium", popularDishes: ["karahi"] }),
  r({ name: "Olive Garden Abbottabad", city: "Abbottabad", cuisine: ["continental", "pakistani"], categories: ["casual", "outdoor"], priceRange: "medium", popularDishes: ["steak", "pasta"], outdoor: true }),
  r({ name: "KFC Abbottabad", city: "Abbottabad", cuisine: ["fast food"], categories: ["casual", "budget"], priceRange: "low", popularDishes: ["zinger"] }),
  r({ name: "Café de' Palate", city: "Abbottabad", cuisine: ["cafe"], categories: ["cafe", "quiet"], priceRange: "medium", hours: cafe, popularDishes: ["coffee", "sandwich"] }),
  r({ name: "Shinwari Restaurant", city: "Abbottabad", cuisine: ["pakistani", "bbq"], categories: ["casual"], priceRange: "low", popularDishes: ["tikka", "karahi"] }),
  p({ name: "Ilyasi Mosque", city: "Abbottabad", categories: ["historical", "cultural"], venueType: "mosque" }),
  p({ name: "Shimla Hill", city: "Abbottabad", categories: ["viewpoint", "outdoor", "date"], venueType: "viewpoint" }),
  p({ name: "Thandiani", city: "Abbottabad", categories: ["nature", "adventure", "outdoor"], venueType: "hill station" }),
  p({ name: "Abbottabad Club Park", city: "Abbottabad", categories: ["park", "walk"], venueType: "park" }),
  p({ name: "Sarban Hills", city: "Abbottabad", categories: ["nature", "outdoor"], venueType: "hills" }),

  r({ name: "Pines Hotel Restaurant", city: "Murree", cuisine: ["pakistani", "continental"], categories: ["family", "view"], priceRange: "high", popularDishes: ["karahi", "soup"], outdoor: true }),
  r({ name: "Usmania Murree", city: "Murree", cuisine: ["pakistani"], categories: ["family"], priceRange: "medium", popularDishes: ["karahi"] }),
  r({ name: "Chaaye Khana Murree", city: "Murree", cuisine: ["cafe", "pakistani"], categories: ["cafe", "casual", "outdoor"], priceRange: "medium", hours: cafe, popularDishes: ["chai", "paratha"] }),
  r({ name: "Lockwood Hotel dining", city: "Murree", cuisine: ["continental"], categories: ["quiet", "romantic"], priceRange: "high", popularDishes: ["steak", "soup"] }),
  r({ name: "Mall Road food stalls", city: "Murree", cuisine: ["street food"], categories: ["casual", "budget", "food"], priceRange: "low", popularDishes: ["corn", "pakora"] }),
  p({ name: "Mall Road", city: "Murree", categories: ["shopping", "walk", "date", "family"], venueType: "promenade" }),
  p({ name: "Pindi Point", city: "Murree", categories: ["viewpoint", "outdoor"], venueType: "viewpoint" }),
  p({ name: "Kashmir Point", city: "Murree", categories: ["viewpoint", "outdoor", "date"], venueType: "viewpoint" }),
  p({ name: "Patriata chairlift", city: "Murree", categories: ["adventure", "outdoor", "family"], venueType: "activity" }),
  p({ name: "Bhurban", city: "Murree", categories: ["nature", "quiet", "outdoor"], venueType: "hill" }),

  r({ name: "Hotel Gilgit dining", city: "Gilgit", cuisine: ["pakistani", "local"], categories: ["family"], priceRange: "medium", popularDishes: ["chapshuro", "soup"] }),
  r({ name: "Pathan Hotel", city: "Gilgit", cuisine: ["pakistani"], categories: ["casual", "budget"], priceRange: "low", popularDishes: ["karahi", "daal"] }),
  r({ name: "Rakaposhi View Restaurant", city: "Gilgit", cuisine: ["pakistani"], categories: ["view", "outdoor"], priceRange: "medium", popularDishes: ["local stew"], outdoor: true }),
  r({ name: "Café de Hunza Gilgit", city: "Gilgit", cuisine: ["cafe"], categories: ["cafe", "quiet"], priceRange: "medium", hours: cafe, popularDishes: ["walnut cake", "coffee"] }),
  r({ name: "Madina Bakery Café", city: "Gilgit", cuisine: ["bakery"], categories: ["cafe", "budget"], priceRange: "low", hours: cafe, popularDishes: ["bread", "tea"] }),
  p({ name: "Gilgit River viewpoint", city: "Gilgit", categories: ["nature", "outdoor", "date"], venueType: "viewpoint" }),
  p({ name: "Kargah Buddha", city: "Gilgit", categories: ["historical", "cultural"], venueType: "heritage" }),
  p({ name: "NLI Market", city: "Gilgit", categories: ["shopping", "cultural"], venueType: "market" }),
  p({ name: "Monument Chowk", city: "Gilgit", categories: ["walk", "cultural"], venueType: "square" }),
  p({ name: "Naltar day trip start", city: "Gilgit", categories: ["adventure", "nature"], venueType: "trailhead" }),

  r({ name: "K2 Motel restaurant", city: "Skardu", cuisine: ["pakistani", "local"], categories: ["family", "view"], priceRange: "medium", popularDishes: ["local trout", "soup"] }),
  r({ name: "Mashabrum Hotel dining", city: "Skardu", cuisine: ["pakistani"], categories: ["family"], priceRange: "medium", popularDishes: ["karahi"] }),
  r({ name: "Skardu bazaar dhabas", city: "Skardu", cuisine: ["pakistani"], categories: ["casual", "budget"], priceRange: "low", popularDishes: ["daal", "roti"] }),
  r({ name: "Café De Hunza Skardu", city: "Skardu", cuisine: ["cafe"], categories: ["cafe", "quiet"], priceRange: "medium", hours: cafe, popularDishes: ["coffee", "cake"] }),
  r({ name: "Shangrila resort dining", city: "Skardu", cuisine: ["continental", "pakistani"], categories: ["luxury", "romantic", "view"], priceRange: "high", popularDishes: ["trout", "bbq"], outdoor: true }),
  p({ name: "Shangrila Lower Kachura Lake", city: "Skardu", categories: ["nature", "date", "outdoor", "luxury"], venueType: "lake" }),
  p({ name: "Satpara Lake", city: "Skardu", categories: ["nature", "outdoor", "adventure"], venueType: "lake" }),
  p({ name: "Skardu Fort (Kharpocho)", city: "Skardu", categories: ["historical", "viewpoint"], venueType: "fort" }),
  p({ name: "Cold Desert Katpana", city: "Skardu", categories: ["nature", "adventure", "outdoor"], venueType: "desert" }),
  p({ name: "Buddha Rock", city: "Skardu", categories: ["historical", "cultural"], venueType: "heritage" }),
];

export function catalogForCity(city: string, kind?: "restaurant" | "place") {
  return CATALOG_VENUES.filter((v) => v.city.toLowerCase() === city.toLowerCase() && (!kind || v.kind === kind));
}
