export const PROFILE_FIELDS = [
  { key: "personality", label: "Personality / preferences", group: "about" },
  { key: "communication_style", label: "Communication style", group: "about" },
  { key: "makes_happy", label: "Things that make her happy", group: "about" },
  { key: "upsets", label: "Things that upset her", group: "about" },
  { key: "calms", label: "Things that calm her", group: "about" },
  { key: "flowers", label: "Favorite flowers", group: "favorites" },
  { key: "colors", label: "Favorite colors", group: "favorites" },
  { key: "foods", label: "Favorite foods", group: "favorites" },
  { key: "songs", label: "Favorite songs", group: "favorites" },
  { key: "movies", label: "Favorite movies", group: "favorites" },
  { key: "activities", label: "Favorite activities", group: "favorites" },
  { key: "places", label: "Favorite places", group: "favorites" },
  { key: "gifts", label: "Favorite gifts", group: "favorites" },
  { key: "apology_style", label: "How she prefers apologies", group: "conflict" },
  { key: "conflict_style", label: "Communication during conflict", group: "conflict" },
  { key: "wants_space", label: "Likes space after an argument (yes/no)", group: "conflict" },
  { key: "message_length", label: "Preferred message length (short/medium/long)", group: "conflict" },
  { key: "romantic_style", label: "Preferred romantic style", group: "style" },
  { key: "humor", label: "Preferred humor", group: "style" },
  { key: "memories_note", label: "Important memories", group: "history" },
  { key: "promises_note", label: "Important promises", group: "history" },
  { key: "current_goals", label: "Current goals", group: "now" },
  { key: "current_concerns", label: "Current concerns", group: "now" },
  { key: "partner_instagram", label: "Her Instagram username (for Send)", group: "send" },
  { key: "partner_whatsapp", label: "Her WhatsApp number with country code", group: "send" },
  { key: "partner_facebook", label: "Her Facebook or Messenger username", group: "send" },
  { key: "partner_email", label: "Her email address", group: "send" },
  { key: "user_city", label: "Your city (no home address — e.g. Islamabad)", group: "city" },
  { key: "partner_cuisines", label: "Her favorite cuisines", group: "food" },
  { key: "partner_dishes", label: "Her favorite dishes", group: "food" },
  { key: "partner_restaurants", label: "Her favorite restaurants", group: "food" },
  { key: "partner_drinks", label: "Her favorite drinks", group: "food" },
  { key: "partner_desserts", label: "Her favorite desserts", group: "food" },
  { key: "partner_food_dislikes", label: "Foods she dislikes", group: "food" },
  { key: "partner_allergies", label: "Allergies or diet notes she shared", group: "food" },
  { key: "partner_spice", label: "Her spice preference", group: "food" },
  { key: "partner_diet", label: "Vegetarian / non-vegetarian preference", group: "food" },
  { key: "partner_budget", label: "Preferred dining budget (low / medium / high)", group: "food" },
  { key: "partner_dining_env", label: "Preferred dining environment", group: "food" },
  { key: "user_cuisines", label: "Your favorite cuisines", group: "food" },
  { key: "user_dishes", label: "Your favorite dishes", group: "food" },
  { key: "user_drinks", label: "Your favorite drinks", group: "food" },
  { key: "user_desserts", label: "Your favorite desserts", group: "food" },
  { key: "user_food_dislikes", label: "Foods you dislike", group: "food" },
  { key: "user_budget", label: "Your dining budget (low / medium / high)", group: "food" },
] as const;

export type ProfileKey = (typeof PROFILE_FIELDS)[number]["key"];
